# Site settings
title: Rodrigo Auditore
description: Personal Page for Rodrigo Auditore
baseurl: "rodrigoauditore.github.io" 
# the subpath of your site, e.g. /blog
url: "rodrigoauditore.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rodrigo Auditore
user_description: I'm Rodrigo Auditore and I'm a result focused individual who's always striving to improve. I'm also a tech enthusiast. As of late, I've been studying for ESCP's Master in Management in Paris, France. I'm currently looking for my next challenging experience in a multicultural environment.
user_title: ESCP Master in Management Student
email: rodrigoauditore@gmail.com
# twitter_username: lorem_ipsum
github_username:  rodrigoauditore
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-156902330-1"

exclude: ['package.json', 'src' , 'node_modules']
